### ISSUE TITLE
It's looking bad at the moment

### ISSUE THREAD

**Issue by jserodio** [wilfredwee/australis-dark#1]
Firefox Developer Edition v51.0a2 (2016-09-23) (64-bit)

**Comment by wilfredwee** [comment]
Hi, can I get your OS and version?

**Comment by wilfredwee** [comment]
I've updated it to work with FF v51. Please close the issue once you confirm that it is fixed. :)

**Comment by jserodio** [comment]
We are back to normal! thank you so much man <3
